### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by devaharikrishnan** [john-doherty/node-iframe-replacement#8]
C:\Users\ADMIN\myapp\node_modules\node-iframe-replacement\example>node server.js
Server running... Visit http://localhost:8080 in your browser
C:\Users\ADMIN\myapp\node_modules\cheerio\lib\parse.js:55
    var oldParent = node.parent || node.root,
                                              ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (C:\Users\ADMIN\myapp\node_modules\cheerio\lib\parse.js:55:26)
    at module.exports (C:\Users\ADMIN\myapp\node_modules\cheerio\lib\parse.js:17:11)
    at Function.exports.load (C:\Users\ADMIN\myapp\node_modules\cheerio\lib\static.js:19:14)
    at C:\Users\ADMIN\myapp\node_modules\node-iframe-replacement\lib\node-iframe-replacement.js:37:41
    at Immediate.<anonymous> (C:\Users\ADMIN\myapp\node_modules\express-handlebars\lib\utils.js:18:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by aliasfoxkde** [comment]
This appears to be an introduced bug when modifying the code. This error is generally related to "Error: Invalid URI". So I'd recommend making sure the URL and protocol are correct.
